#pragma once

#include <stdio.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/event.h>
#include <sys/epoll.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <stdint.h>
#include <time.h>
#include <fcntl.h>
#include <err.h>
#include <errno.h>
#include "user.h"
#include "room.h"
#include "utils.h"
#include "db.h"
#include "../aes/aes.h"
#include "command.h"
#include "server.h"